[package]
name = "render"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
map = { path = "../map" }
embedded-graphics = "0.6.2"
log = "0.4.14"
nalgebra-glm = "0.11.0"
line_drawing = "0.8.0"

[dev-dependencies]
map = { path = "../map" }
minifb = "0.19.3"
